
exports.GameEventsEnum = {
  FIELD_CREATED: "FIELD_CREATED",
  BALL_ADDED: "BALL_ADDED",
  PADDLE_ADDED: "PADDLE_ADDED",
  BALL_POSITION_CHANGED: "BALL_POSITION_CHANGED",
  PADDLE_POSITION_CHANGED: "PADDLE_POSITION_CHANGED"
};